### ISSUE TITLE
Regarding ECG visualization

### ISSUE THREAD

**Issue by Mohd-ajmal** [mk590901/custom_widget_painter#1]
Hi!, currently i am working on a project which is exactly what you did and i already made ECG visualization with a package which is slidable_line_chart working perfectly but the thing is client need animation like EXACT ECG which is in hospital like i attached below image i am trying to do this for past 20 days but un luckily which is not done yet so, can you please help me out to do that, this is my whats app number 8870749245. if you have enough time please ping me on whats app. 

Note:- i have entire package code so we can customise like what we need.

![image](https://github.com/mk590901/custom_widget_painter/assets/90542307/061415c5-1f19-46e6-9870-3395c3eb4199)

**Comment by mk590901** [comment]
You can try to do this by dividing the imaged signal into several pieces. Each of these pieces should be drawn in a color slightly different from the color of the previous piece (something like a gradient). These bit pieces don't have to be the same size.
